org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Minecraft
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.13

# Environment Properties
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.77
neo_version_range=[21.1.0,)
loader_version_range=[4,)

# Mod Properties
mod_id=etched
mod_name=Etched
mod_license=GPLv3
mod_version=5.0.0
mod_authors=Ocelot, Jackson, Farcr (Art), AstraZoey (Sound Design)
mod_description=A new form of entertainment.
mod_group_id=gg.moonflower
