name: Release
on: [workflow_dispatch] # Manual trigger
env:
  CI: 'true'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: release
    container:
      image: mcr.microsoft.com/openjdk/jdk:21-ubuntu
      options: --user root
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Make Gradle Wrapper Executable
        run: chmod +x ./gradlew
      - name: Execute Gradle build
        run: ./gradlew build
      - name: Publish mods
        run: ./gradlew publishMods
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}